### ISSUE TITLE
version 1.1.0 not running issue

### ISSUE THREAD

**Issue by yoyomomo21** [Totsukawaii/UndownUnlock#15]
after running 'launch.bat' as admin it shows
```
Miniconda is already installed.
Running Injector...
Traceback (most recent call last):
  File "inject.py", line 1, in <module>
    import psutil  # You'll need to install psutil: pip install psutil
ModuleNotFoundError: No module named 'psutil'
Running Controller...
```

after running that command in windows terminal, i get:
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psutil in c:\users\USERNAME\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (5.9.8)
```

**Comment by Totsukawaii** [comment]
Make sure your file path doesn't have any spaces, brakets or other symbols

**Comment by yoyomomo21** [comment]
> Make sure your file path doesn't have any spaces, brakets or other symbols

i just have it in my downloads so its C:\Users\USERNAME\Downloads\UndownUnlock-v1.1.0  i think this should be fine,i have also tried changing to C:\Users\USERNAME\Downloads\UndownUnlock but that still gives
Miniconda is already installed.
Running Injector...
Traceback (most recent call last):
  File "inject.py", line 1, in <module>
    import psutil  # You'll need to install psutil: pip install psutil
ModuleNotFoundError: No module named 'psutil'
Running Controller...


version 1.0.2 works but that a little dated

**Comment by Totsukawaii** [comment]
currently i have no way to test LDB so you have to use v1.0.2 for now

**Comment by Prashithshetty** [comment]
i got the same issue but i use linux but in windows i dont get this error plz help me
